const { MongoClient } = require('mongodb');
const dotenv = require('dotenv');
dotenv.config();

const client = new MongoClient(process.env.MONGO_URI);

const questions = [ /* paste your 45 questions array here */
    {
        id: 'jee1-q1',
        branchId: 'jee',
        testId: 'jee-1',
        questionText: 'What is the SI unit of pressure?',
        options: ['Pascal', 'Newton', 'Joule', 'Watt'],
        correctAnswer: 0,
        explanation: 'The SI unit of pressure is Pascal (Pa).',
        difficulty: 'easy',
      },
      {
        id: 'jee1-q2',
        branchId: 'jee',
        testId: 'jee-1',
        questionText: 'Which of the following is a vector quantity?',
        options: ['Mass', 'Speed', 'Displacement', 'Work'],
        correctAnswer: 2,
        explanation: 'Displacement has both magnitude and direction, hence it is a vector.',
        difficulty: 'easy',
      },
      {
        id: 'jee1-q3',
        branchId: 'jee',
        testId: 'jee-1',
        questionText: 'What is the derivative of cos(x)?',
        options: ['-sin(x)', 'cos(x)', 'sin(x)', '-cos(x)'],
        correctAnswer: 0,
        explanation: 'The derivative of cos(x) is -sin(x).',
        difficulty: 'medium',
      },
      {
        id: 'jee1-q4',
        branchId: 'jee',
        testId: 'jee-1',
        questionText: 'Which gas is used in the Haber process to produce ammonia?',
        options: ['Oxygen', 'Hydrogen', 'Methane', 'Carbon dioxide'],
        correctAnswer: 1,
        explanation: 'Hydrogen reacts with nitrogen in the Haber process.',
        difficulty: 'medium',
      },
      {
        id: 'jee1-q5',
        branchId: 'jee',
        testId: 'jee-1',
        questionText: 'Which of the following is a non-metal?',
        options: ['Sodium', 'Magnesium', 'Sulphur', 'Calcium'],
        correctAnswer: 2,
        explanation: 'Sulphur is a non-metal.',
        difficulty: 'easy',
      },
    
      // jee-2
      {
        id: 'jee2-q1',
        branchId: 'jee',
        testId: 'jee-2',
        questionText: 'Which law states that current is directly proportional to voltage?',
        options: ['Faraday’s Law', 'Ohm’s Law', 'Kirchhoff’s Law', 'Lenz’s Law'],
        correctAnswer: 1,
        explanation: 'Ohm’s Law: V = IR.',
        difficulty: 'easy',
      },
      {
        id: 'jee2-q2',
        branchId: 'jee',
        testId: 'jee-2',
        questionText: 'What is the atomic number of Oxygen?',
        options: ['6', '7', '8', '9'],
        correctAnswer: 2,
        explanation: 'Oxygen has an atomic number of 8.',
        difficulty: 'easy',
      },
      {
        id: 'jee2-q3',
        branchId: 'jee',
        testId: 'jee-2',
        questionText: 'Which of the following is not a thermodynamic process?',
        options: ['Isobaric', 'Isochoric', 'Isothermal', 'Isomagnetic'],
        correctAnswer: 3,
        explanation: 'Isomagnetic is not a thermodynamic process.',
        difficulty: 'medium',
      },
      {
        id: 'jee2-q4',
        branchId: 'jee',
        testId: 'jee-2',
        questionText: 'Which element has the electronic configuration 1s² 2s² 2p⁶?',
        options: ['Neon', 'Oxygen', 'Fluorine', 'Sodium'],
        correctAnswer: 0,
        explanation: 'Neon has the electronic configuration 1s² 2s² 2p⁶.',
        difficulty: 'medium',
      },
      {
        id: 'jee2-q5',
        branchId: 'jee',
        testId: 'jee-2',
        questionText: 'Which branch of mathematics deals with rates of change?',
        options: ['Algebra', 'Geometry', 'Calculus', 'Trigonometry'],
        correctAnswer: 2,
        explanation: 'Calculus is the mathematical study of change.',
        difficulty: 'medium',
      },
    
      // jee-3
      {
        id: 'jee3-q1',
        branchId: 'jee',
        testId: 'jee-3',
        questionText: 'Which of these is an example of a p-block element?',
        options: ['Na', 'Mg', 'Al', 'Ca'],
        correctAnswer: 2,
        explanation: 'Aluminium (Al) is a p-block element.',
        difficulty: 'medium',
      },
      {
        id: 'jee3-q2',
        branchId: 'jee',
        testId: 'jee-3',
        questionText: 'Find the integral of x dx.',
        options: ['x', 'x²/2', 'x³/3', 'log(x)'],
        correctAnswer: 1,
        explanation: '∫x dx = x²/2 + C.',
        difficulty: 'easy',
      },
      {
        id: 'jee3-q3',
        branchId: 'jee',
        testId: 'jee-3',
        questionText: 'The value of Planck’s constant is closest to:',
        options: ['6.63×10⁻³⁴ J·s', '9.8 m/s²', '1.6×10⁻¹⁹ C', '3×10⁸ m/s'],
        correctAnswer: 0,
        explanation: 'Planck’s constant = 6.63×10⁻³⁴ J·s.',
        difficulty: 'medium',
      },
      {
        id: 'jee3-q4',
        branchId: 'jee',
        testId: 'jee-3',
        questionText: 'What is the slope of a tangent line to y = x² at x = 2?',
        options: ['2', '4', '8', '16'],
        correctAnswer: 1,
        explanation: 'Derivative of x² is 2x. At x=2, slope = 4.',
        difficulty: 'medium',
      },
      {
        id: 'jee3-q5',
        branchId: 'jee',
        testId: 'jee-3',
        questionText: 'Which metal is liquid at room temperature?',
        options: ['Iron', 'Mercury', 'Aluminium', 'Copper'],
        correctAnswer: 1,
        explanation: 'Mercury is liquid at room temperature.',
        difficulty: 'easy',
      },
    
      // ---------------------- NEET ----------------------
      // neet-1
      {
        id: 'neet1-q1',
        branchId: 'neet',
        testId: 'neet-1',
        questionText: 'Which tissue connects muscles to bones?',
        options: ['Ligaments', 'Tendons', 'Cartilage', 'Areolar tissue'],
        correctAnswer: 1,
        explanation: 'Tendons connect muscles to bones.',
        difficulty: 'easy',
      },
      {
        id: 'neet1-q2',
        branchId: 'neet',
        testId: 'neet-1',
        questionText: 'What is the primary function of red blood cells?',
        options: ['Fight infections', 'Clot blood', 'Transport oxygen', 'Digest food'],
        correctAnswer: 2,
        explanation: 'RBCs carry oxygen using hemoglobin.',
        difficulty: 'easy',
      },
      {
        id: 'neet1-q3',
        branchId: 'neet',
        testId: 'neet-1',
        questionText: 'Which part of the brain controls balance?',
        options: ['Cerebrum', 'Medulla', 'Cerebellum', 'Pons'],
        correctAnswer: 2,
        explanation: 'Cerebellum controls body balance and coordination.',
        difficulty: 'medium',
      },
      {
        id: 'neet1-q4',
        branchId: 'neet',
        testId: 'neet-1',
        questionText: 'Which vitamin is known as ascorbic acid?',
        options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin B12'],
        correctAnswer: 1,
        explanation: 'Vitamin C is also called ascorbic acid.',
        difficulty: 'easy',
      },
      {
        id: 'neet1-q5',
        branchId: 'neet',
        testId: 'neet-1',
        questionText: 'How many chambers are there in the human heart?',
        options: ['2', '3', '4', '5'],
        correctAnswer: 2,
        explanation: 'The human heart has 4 chambers: 2 atria and 2 ventricles.',
        difficulty: 'easy',
      },
    
      // neet-2 & neet-3 already partly included earlier — I can generate the rest upon your confirmation.
    // ---------------------- NEET ----------------------
    // neet-2
    {
      id: 'neet2-q1',
      branchId: 'neet',
      testId: 'neet-2',
      questionText: 'Which organ produces insulin in the human body?',
      options: ['Liver', 'Pancreas', 'Stomach', 'Kidney'],
      correctAnswer: 1,
      explanation: 'Pancreas produces insulin, which regulates blood sugar.',
      difficulty: 'medium',
    },
    {
      id: 'neet2-q2',
      branchId: 'neet',
      testId: 'neet-2',
      questionText: 'Which part of the nephron is responsible for filtration?',
      options: ['Loop of Henle', 'Bowman’s capsule', 'Collecting duct', 'Distal tubule'],
      correctAnswer: 1,
      explanation: 'Bowman’s capsule filters blood in the nephron.',
      difficulty: 'medium',
    },
    {
      id: 'neet2-q3',
      branchId: 'neet',
      testId: 'neet-2',
      questionText: 'What is the function of xylem in plants?',
      options: ['Photosynthesis', 'Water transport', 'Food storage', 'Hormone secretion'],
      correctAnswer: 1,
      explanation: 'Xylem transports water and minerals from roots to leaves.',
      difficulty: 'easy',
    },
    {
      id: 'neet2-q4',
      branchId: 'neet',
      testId: 'neet-2',
      questionText: 'Which of the following is an example of a connective tissue?',
      options: ['Muscle', 'Nerve', 'Cartilage', 'Epithelial'],
      correctAnswer: 2,
      explanation: 'Cartilage is a flexible connective tissue.',
      difficulty: 'easy',
    },
    {
      id: 'neet2-q5',
      branchId: 'neet',
      testId: 'neet-2',
      questionText: 'Which hormone regulates calcium levels in the blood?',
      options: ['Insulin', 'Thyroxine', 'Parathyroid hormone', 'Adrenaline'],
      correctAnswer: 2,
      explanation: 'Parathyroid hormone increases blood calcium levels.',
      difficulty: 'medium',
    },
    
    // neet-3
    {
      id: 'neet3-q1',
      branchId: 'neet',
      testId: 'neet-3',
      questionText: 'Which structure in the eye controls the size of the pupil?',
      options: ['Retina', 'Cornea', 'Iris', 'Lens'],
      correctAnswer: 2,
      explanation: 'The iris regulates the size of the pupil.',
      difficulty: 'easy',
    },
    {
      id: 'neet3-q2',
      branchId: 'neet',
      testId: 'neet-3',
      questionText: 'What type of immunity is provided by vaccines?',
      options: ['Natural passive', 'Artificial active', 'Natural active', 'Artificial passive'],
      correctAnswer: 1,
      explanation: 'Vaccines provide artificial active immunity.',
      difficulty: 'medium',
    },
    {
      id: 'neet3-q3',
      branchId: 'neet',
      testId: 'neet-3',
      questionText: 'Which gas is released during photosynthesis?',
      options: ['Carbon dioxide', 'Nitrogen', 'Oxygen', 'Hydrogen'],
      correctAnswer: 2,
      explanation: 'Oxygen is released as a by-product of photosynthesis.',
      difficulty: 'easy',
    },
    {
      id: 'neet3-q4',
      branchId: 'neet',
      testId: 'neet-3',
      questionText: 'Which part of the brain controls respiration?',
      options: ['Cerebrum', 'Medulla oblongata', 'Cerebellum', 'Hypothalamus'],
      correctAnswer: 1,
      explanation: 'Medulla oblongata controls involuntary functions like breathing.',
      difficulty: 'medium',
    },
    {
      id: 'neet3-q5',
      branchId: 'neet',
      testId: 'neet-3',
      questionText: 'Which vitamin helps in blood clotting?',
      options: ['Vitamin A', 'Vitamin C', 'Vitamin K', 'Vitamin D'],
      correctAnswer: 2,
      explanation: 'Vitamin K is essential for the clotting of blood.',
      difficulty: 'easy',
    },
      // ---------------------- UPSC ----------------------
      // upsc-1
      {
        id: 'upsc1-q1',
        branchId: 'upsc',
        testId: 'upsc-1',
        questionText: 'When did India gain independence?',
        options: ['15 August 1947', '26 January 1950', '2 October 1947', '26 November 1949'],
        correctAnswer: 0,
        explanation: 'India became independent on 15 August 1947.',
        difficulty: 'easy',
      },
      {
        id: 'upsc1-q2',
        branchId: 'upsc',
        testId: 'upsc-1',
        questionText: 'Which river is known as the "Sorrow of Bihar"?',
        options: ['Yamuna', 'Ganga', 'Kosi', 'Sutlej'],
        correctAnswer: 2,
        explanation: 'Kosi River is called the "Sorrow of Bihar" due to frequent floods.',
        difficulty: 'medium',
      },
      {
        id: 'upsc1-q3',
        branchId: 'upsc',
        testId: 'upsc-1',
        questionText: 'Who is the current Chief Justice of India (2025)?',
        options: ['NV Ramana', 'DY Chandrachud', 'UU Lalit', 'Ranjan Gogoi'],
        correctAnswer: 1,
        explanation: 'As of 2025, DY Chandrachud is the Chief Justice.',
        difficulty: 'medium',
      },
      {
        id: 'upsc1-q4',
        branchId: 'upsc',
        testId: 'upsc-1',
        questionText: 'Which article deals with the fundamental right to equality?',
        options: ['Article 14', 'Article 19', 'Article 32', 'Article 370'],
        correctAnswer: 0,
        explanation: 'Article 14 provides for equality before the law.',
        difficulty: 'easy',
      },
      {
        id: 'upsc1-q5',
        branchId: 'upsc',
        testId: 'upsc-1',
        questionText: 'Which city is known as the Silicon Valley of India?',
        options: ['Hyderabad', 'Pune', 'Chennai', 'Bangalore'],
        correctAnswer: 3,
        explanation: 'Bangalore is called the Silicon Valley of India.',
        difficulty: 'easy',
      },
      // upsc-2
    {
      id: 'upsc2-q1',
      branchId: 'upsc',
      testId: 'upsc-2',
      questionText: 'Which is the longest river in India?',
      options: ['Yamuna', 'Ganga', 'Godavari', 'Brahmaputra'],
      correctAnswer: 1,
      explanation: 'The Ganga is the longest river within India.',
      difficulty: 'easy',
    },
    {
      id: 'upsc2-q2',
      branchId: 'upsc',
      testId: 'upsc-2',
      questionText: 'Which movement was led by Mahatma Gandhi in 1942?',
      options: ['Non-Cooperation', 'Dandi March', 'Khilafat Movement', 'Quit India Movement'],
      correctAnswer: 3,
      explanation: 'The Quit India Movement was launched in 1942.',
      difficulty: 'easy',
    },
    {
      id: 'upsc2-q3',
      branchId: 'upsc',
      testId: 'upsc-2',
      questionText: 'Which country shares the longest border with India?',
      options: ['China', 'Pakistan', 'Bangladesh', 'Nepal'],
      correctAnswer: 2,
      explanation: 'India shares its longest border with Bangladesh.',
      difficulty: 'medium',
    },
    {
      id: 'upsc2-q4',
      branchId: 'upsc',
      testId: 'upsc-2',
      questionText: 'Who was the founder of the Maurya Empire?',
      options: ['Ashoka', 'Chandragupta Maurya', 'Bindusara', 'Kautilya'],
      correctAnswer: 1,
      explanation: 'Chandragupta Maurya founded the Maurya Empire with the help of Chanakya.',
      difficulty: 'medium',
    },
    {
      id: 'upsc2-q5',
      branchId: 'upsc',
      testId: 'upsc-2',
      questionText: 'Which planet is known as the Red Planet?',
      options: ['Venus', 'Mars', 'Jupiter', 'Mercury'],
      correctAnswer: 1,
      explanation: 'Mars is called the Red Planet due to iron oxide on its surface.',
      difficulty: 'easy',
    },
    
    // upsc-3
    {
      id: 'upsc3-q1',
      branchId: 'upsc',
      testId: 'upsc-3',
      questionText: 'Who was the first woman Prime Minister of India?',
      options: ['Indira Gandhi', 'Sonia Gandhi', 'Sarojini Naidu', 'Meira Kumar'],
      correctAnswer: 0,
      explanation: 'Indira Gandhi was the first woman Prime Minister of India.',
      difficulty: 'easy',
    },
    {
      id: 'upsc3-q2',
      branchId: 'upsc',
      testId: 'upsc-3',
      questionText: 'What is the capital of Uttarakhand?',
      options: ['Dehradun', 'Nainital', 'Haridwar', 'Mussoorie'],
      correctAnswer: 0,
      explanation: 'Dehradun is the capital city of Uttarakhand.',
      difficulty: 'easy',
    },
    {
      id: 'upsc3-q3',
      branchId: 'upsc',
      testId: 'upsc-3',
      questionText: 'Which is the highest civilian award in India?',
      options: ['Padma Shri', 'Padma Bhushan', 'Padma Vibhushan', 'Bharat Ratna'],
      correctAnswer: 3,
      explanation: 'Bharat Ratna is India’s highest civilian award.',
      difficulty: 'medium',
    },
    {
      id: 'upsc3-q4',
      branchId: 'upsc',
      testId: 'upsc-3',
      questionText: 'Which Indian state has the longest coastline?',
      options: ['Maharashtra', 'Tamil Nadu', 'Gujarat', 'Andhra Pradesh'],
      correctAnswer: 2,
      explanation: 'Gujarat has the longest coastline in India.',
      difficulty: 'medium',
    },
    {
      id: 'upsc3-q5',
      branchId: 'upsc',
      testId: 'upsc-3',
      questionText: 'Which language is included in the 8th Schedule of Indian Constitution?',
      options: ['English', 'Sanskrit', 'Tulu', 'Bhojpuri'],
      correctAnswer: 1,
      explanation: 'Sanskrit is one of the 22 languages in the 8th Schedule.',
      difficulty: 'medium',
    },
 ];

async function seedDB() {
  try {
    await client.connect();
    const db = client.db('exampro');
    const collection = db.collection('questions');

    // Optional: clear existing
    await collection.deleteMany({});
    
    // Insert new
    await collection.insertMany(questions);
    console.log('✅ Questions inserted successfully!');
  } catch (error) {
    console.error('❌ Error inserting:', error);
  } finally {
    await client.close();
  }
}

seedDB();
